### ISSUE TITLE
entity 생성

### ISSUE THREAD

**Issue by docoding0228** [nbcamp-java-5-14/javafeed#1]
## Description
entity 생성

## To-do
- [ ] user entity 생성
- [ ] news feed entity 생성
- [ ] userstatus enum 생성

## ETC
기타사항
