### ISSUE TITLE
필수 기능 구현 예외처리 및 성공처리

### ISSUE THREAD

**Issue by docoding0228** [nbcamp-java-5-14/javafeed#7]
## Description
필수 기능 구현 예외처리 및 성공처리

## To-do
- [ ] enums 패키지 생성
- [ ] exception 패키지 생성
- [ ] enums 클래스 생성, ResponseStatus, ErrorType

## ETC
기타사항
